services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: 
      context: ./user
      dockerfile: dockerfile
    image: user:1.0.0
    container_name: user:1.0.0
    depends_on: redis

  cart:
    build:
      context: ./cart
      dockerfile: dockerfile
    image: cart:1.0.0
    container_name: cart:1.0.0
  

  mongodb:
    build:
      context: ./mongodb
      dockerfile: dockerfile
    image: mongodb:1.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis:1.0.0

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually