services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: 
      context: ./user
      dockerfile: dockerfile
    image: user:1.0.0
    container_name: user:1.0.0

  cart:
    build:
      context: ./cart
      dockerfile: dockerfile
    image: cart:1.0.0
    container_name: cart:1.0.0
  

  mongodb:
    build:
      context: ./mongodb
      dockerfile: dockerfile
    image: mongodb:1.0.0
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually