services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: roboshop/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: 
      context: ./user
      dockerfile: dockerfile
    image: roboshop/user:1.0.0
    container_name: user
    depends_on: 
    - redis
    - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: roboshop/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart

  cart:
    build:
      context: ./cart
      dockerfile: dockerfile
    image: roboshop/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  

  mongodb:
    build:
      context: ./mongodb
      dockerfile: dockerfile
    image: roboshop/mongodb:1.0.0
    container_name: mongodb
    

  redis:
    build:
        context: ./frontend
        dockerfile: dockerfile
    image: roboshop/redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually