FROM node:20.20.2-alpine3.23 as builder
WORKDIR /app
COPY package.json .
COPY *.js .
RUN npm install

FROM node:20.20.2-alpine3.23 as builder
WORKDIR /app
EXPOSE 8080
COPY --from=builder /app /app
#this env is going to be handeled in k8s configmap
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
RUN chown -R roboshop:roboshop /app
USER roboshop
CMD ["server.js"]
ENTRYPOINT ["node"]
