FROM node:20.20.2-alpine3.23 AS builder
WORKDIR /app
COPY package.json .
COPY *.js .
RUN npm install



FROM node:20.20.2-alpine3.23 
WORKDIR /app
EXPOSE 8080
COPY --from=builder /app /app
#this env is going to be handeled in k8s configmap
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
RUN chown -R roboshop:roboshop /app
USER roboshop
CMD ["server.js"]
ENTRYPOINT ["node"]


# FROM node:20.20.2-alpine3.23
# #this creates /app and move  there
# WORKDIR /app1
# ENV MONGO="true" \
#     MONGO_URL="mongodb://mongodb:27017/catalogue"\
#     REDIS_URL="redis://redis:6379"
# EXPOSE 8080
# COPY package.json .
# COPY *.js .
# RUN npm install
# CMD ["node", "server.js"]